services:
  firebase-emulators:
    image: andreysenov/firebase-tools
    ports:
      - '4000:4000'
      - '9099:9099'
      - '8081:8081'
    volumes:
      - ./firebase.json:/home/node/firebase.json
    command: firebase emulators:start --project demo-project

  api:
    build: .
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - FRONTEND_ORIGIN=http://localhost:3000
      - FIRESTORE_EMULATOR_HOST=firebase-emulators:8081
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulators:9099
    depends_on:
      - firebase-emulators

  web:
    build:
      context: ../nc-user-profile-web
      args:
        VITE_API_BASE_URL: http://localhost:8080
        VITE_FIREBASE_API_KEY: demo-api-key
        VITE_FIREBASE_AUTH_DOMAIN: demo-project.firebaseapp.com
        VITE_FIREBASE_PROJECT_ID: demo-project
        VITE_FIREBASE_AUTH_EMULATOR_URL: http://localhost:9099
    ports:
      - '3000:80'
    depends_on:
      - api
